[build]
builder = "NIXPACKS"
nixpacksVersion = "1.13.0"
buildCommand = "cd client && npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "3000"
NODE_ENV = "production" 